sudo: false
language: c
matrix:
  include:
    - os: osx
      python: "2.7"
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      python: "3.5"
      env: TRAVIS_PYTHON_VERSION=3.5
    - os: osx
      python: "pypy"
      env: TRAVIS_PYTHON_VERSION=pypy
    - os: linux
      language: python
      python: "2.6"
    - os: linux
      language: python
      python: "2.7"
    - os: linux
      language: python
      python: "3.2"
    - os: linux
      language: python
      python: "3.3"
    - os: linux
      language: python
      python: "3.4"
    - os: linux
      language: python
      python: "3.5"
    - os: linux
      language: python
      python: "pypy"
    - os: linux
      language: python
      python: "pypy3"
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        if [ "$TRAVIS_PYTHON_VERSION" == "3.5" ]; then
            brew install python3;
            /usr/local/bin/pip3 install flake8;
        else
            if [ "$TRAVIS_PYTHON_VERSION" == "pypy" ]; then
                brew install pypy;
                /usr/local/bin/pip_pypy install flake8;
            else
                sudo /usr/bin/easy_install-2.7 flake8;
            fi
        fi
    else
        pip install flake8;
    fi
script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        if [ "$TRAVIS_PYTHON_VERSION" == "3.5" ]; then
            /usr/local/bin/python3 run.py ci;
        else
            if [ "$TRAVIS_PYTHON_VERSION" == "pypy" ]; then
                /usr/local/bin/pypy run.py ci;
            else
                /usr/bin/python2.7 run.py ci;
            fi
        fi
    else
        python run.py ci;
    fi
