version: 2
jobs:
  build-arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: python run.py deps
      - run: python run.py ci-driver
      - run: python3 run.py ci-driver
workflows:
  version: 2
  test:
    jobs:
      - build-arm
